[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=6.5.1",
    "pydantic-settings>=2.12.0",
    "requests>=2.32.5",
    "sseclient-py>=1.9.0",
]
