global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "go-backend"
    static_configs:
      - targets: ["backend:8080"]

  - job_name: "openai-backend"
    static_configs:
      - targets: ["host.docker.internal:8000"]
